services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      #open port 3306 on the container
      - '3306'
    volumes:
    # Endereço para persistir o docker
      - /Users/thiagoaramizo/Developer/api-flask/mysql:/var/lib/mysql